name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REDIS_URL: localhost
      REDIS_PORT: 6379
      MONGODB_URL: mongodb://localhost:27017

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.4.0"

      - name: Install Dependencies
        run: npm install

      - name: Install Dependencies CLI
        run: cd src/CLI && npm install

      - name: Run Tests
        run: npm test
